# Spring boot DevTools
# Live Reload ?? ???
#spring.devtools.livereload.enabled=true
#
## thymeleaf cache ?? ?? (??????? true ??)
#spring.thymeleaf.cache=false
#
#
## h2 DB connection
##spring.datasource.url=jdbc:h2:tcp://localhost/~/test
##spring.datasource.driver-class-name=org.h2.Driver
##spring.datasource.username=sa
#
## MySql DB Connection
## Table-name = boot_jpa
#spring.datasource.username=root
#spring.datasource.password=1234
## Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/boot_jpa?useSSL=false
#
## JPA
#
#
## SQL query
#spring.jpa.show-sql=true
#
## table? ???? ???? ??. ???. table auto create - none
#spring.jpa.hibernate.ddl-auto=none
## SQL first create allow
#spring.jpa.defer-datasource-initialization=true
## use = always, nonUse = never
#spring.sql.init.mode=never
#
##File Server Setting
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.file-size-threshold= 2KB
#spring.servlet.multipart.max-file-size= 500MB
#spring.servlet.multipart.max-request-size=515MB
##spring.servlet.multipart.location=/Users/seokjunKang/intellij-gradle/file
#file.dir=/Users/seokjunKang/intellij-gradle/file/
##file.dir=/home/ubuntu/file-dir // AWS DIR
#
## JWT
#jwt.header=Authorization
## echo 'lucasKang-tech-spring-boot-jwt-tutorial-secret-lucasKang-tech-spring-boot-jwt-tutorial-secret'|base64
#jwt.secret=bHVjYXNLYW5nLXRlY2gtc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC1sdWNhc0thbmctdGVjaC1zcHJpbmctYm9vdC1qd3QtdHV0b3JpYWwtc2VjcmV0Cg==
#jwt.token-validity-in-seconds=86400

# yml setting
spring:
  profiles:
    active: local

  # jpa
  jpa:
    show-sql: true
    properties:
      hibernates:
        format_sql: true
    hibernate:
      ddl-auto: none

  devtools:
    livereload:
      enabled: true

jwt:
  header: Authorization
  secret: bHVjYXNLYW5nLXRlY2gtc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC1sdWNhc0thbmctdGVjaC1zcHJpbmctYm9vdC1qd3QtdHV0b3JpYWwtc2VjcmV0Cg==
  token-validity-in-seconds: 86400

---
# local
spring:
  config:
    activate:
      on-profile: local
  # table name : boot_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_jpa?useSSL=false
    username: root
    password: 1234

  #File Server
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      location: /Users/seokjunKang/intellij-gradle/file
---
# for Docker Images
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.201.49.184:3306/boot_jpa?characterEncoding=UTF-8
    username: root
    password: 1234

  #File Server - AWS
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      location: /home/ubuntu/day-file
