# local
spring:
  config:
    activate:
      on-profile: local
  # table name : boot_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_jpa?useSSL=false
    username: root
    password: 1234

  #File Server
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      location: /Users/seokjunKang/intellij-gradle/file